name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version: 'v22.13.1'
                # You can also change 'lts' to any supported LTS Node.js version.
            - run: npm install -g @testim/testim-cli
            - run: testim --token "bhwCsWDLeh9hLK7UVPUSEsrQTAz8Ukg3eDc1iymChcTaC4btcg" --project "JSckrYFLB4rT2eeyNRKy" --grid "Testim-Grid"
